[project]
name = "cv-assignment-2-grp-8"
version = "0.1.0"
description = "Computer Vision Assignment 2 - Group 8"

requires-python = "==3.10.*"

dependencies = [
    "numpy<2",
    "pandas>=2.2",
    "opencv-python>=4.10",
    "pillow>=10.3",
    "torch>=2.3; platform_machine != 'x86_64' or sys_platform != 'darwin'",
    "torch>=2.0.0,<2.3.0; platform_machine == 'x86_64' and sys_platform == 'darwin'",
    "transformers>=4.41",
    "sentence-transformers>=2.7",
    "scikit-learn>=1.5",
    "av>=12.0",
    "llvmlite>=0.39.0,<0.44.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false
environments = [
    "sys_platform == 'darwin' and platform_machine == 'arm64'",   # Mac Apple Silicon
    "sys_platform == 'darwin' and platform_machine == 'x86_64'",  # Mac Intel
    "sys_platform == 'win32'",                                      # Windows
    "sys_platform == 'linux'",                                      # Linux
]
